# Generated by Django 4.1.1 on 2022-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='can_be_used_count',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
